spring.application.name=care
spring.security.user.name=lucas@gmail.com
spring.security.user.password=lucas
spring.security.login-page=/login

# Mostrar SQL no console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
